name: Run JMeter Tests

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Git repository URL to clone'
        required: true
        type: string
      branch_name:
        description: 'Branch name to checkout'
        required: true
        type: string
      script_name:
        description: 'JMeter test plan file name (.jmx)'
        required: true
        type: string

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Clone target repo and checkout branch
        run: |
          git clone ${{ inputs.repo_url }} target-repo
          cd target-repo
          git checkout ${{ inputs.branch_name }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download JMeter
        run: |
          JMETER_VERSION=5.6.3
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xzf apache-jmeter-$JMETER_VERSION.tgz
          echo "$GITHUB_WORKSPACE/apache-jmeter-$JMETER_VERSION/bin" >> $GITHUB_PATH

      - name: Run JMeter tests
        run: |
          cd target-repo
          ../apache-jmeter-*/bin/jmeter -n -t ${{ inputs.script_name }} -l ../results.jtl

      - name: Archive JMeter results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl
